### PR TITLE
openxt-vusb: Add timeout to device teardown

### PR DESCRIPTION
**Pull request by jandryuk**
I consistently observed a device hanging during unplug in
vusb_usbif_halt's wait_event_interruptible.  There were two outstanding
requests that did not get responses.  The device was physically removed
and backend torn down, so no answers would ever come.

Add a timeout since we know the device is going away when we enter
vusb_usbif_halt.

Signed-off-by: Jason Andryuk <jandryuk@gmail.com>

I set the timeout to 750 milliseconds.  Is this too short or too long?

This fix deserves to go in since the frontend should not wait for responses that never come.  The backend probably wants a fix as well.  I'm not sure, but the backend may not be generating responses for error conditions properly.  Specifically, the on unplug, the backend vusb_setup_urb is repeatedly called returning -ENODEV.  I'm not sure how to get it to stop on the first -ENODEV.

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1894

**Comment by rossphilipson** [comment]
This seems reasonable to me. In fact I may have run into it once or twice but it was not reproducible for me so I did not track it down. As to whether the timeout is reasonable, I would just go with what you have and see how things work out. I don't think it is too long - could be too short.

Thanks
Ross

**Comment by jean-edouard** [comment]
Thank you Ross! Will merge soon.

**Comment by jandryuk** [comment]
Yes, thanks for the review, @rossphilipson

**Pull request merged**
