### PR TITLE
[rfc] debian packaging

### PR DESCRIPTION
**Pull request by cjp256**
Make it really easy to build proper debs from pv-linux-drivers.

### CODE REVIEW

**Comment by rossphilipson** [comment]
The bits to make it easy to build debs looks like good stuffs.

I do have concerns about removing the postinst scripts. I often use those to re-install the DKMS packages during development work (e.g. as per this wiki: https://openxt.atlassian.net/wiki/display/DC/PV+Linux+Drivers). I guess it could be cleaner though instead of all the duplicated scripts.

**Comment by cjp256** [comment]
@rossphilipson , for dev purposes, how about simply:
make && sudo insmod xc-*.ko

Then rmmod [-f] to unload? and try again?

**Comment by rossphilipson** [comment]
That is fine as long as we don't have modules that need to go in the initramfs. The nice thing about the postinst method was that is automatically fixed up the initramfs too.

**Comment by cjp256** [comment]
@rossphilipson gotcha.

When you want to test with it in the initramfs, you could just:
dpkg-buildpackage -uc -us
dpkg -i ../openxt-pv-xc-xxxx.deb

Might take a few more seconds, but you're rebooting anyways :)

**Comment by rossphilipson** [comment]
Fair enough and I can always stash those scripts away for my own use. Will want to update that wiki if we do this. It there a ticket for this?

**Comment by cjp256** [comment]
There is not a ticket.  I can make one if you want.

This is not ready to be merged, because it probably the current deb hacks in the xenclient-oe layer.  This was just a starting point to getting the debian packaging closer to something proper, before flushing out the other required changes.

@jean-edouard what are your thoughts?

**Comment by rossphilipson** [comment]
Yea I would also like to hear other people's thoughts...

**Comment by jean-edouard** [comment]
@cjp256 I wrote the bbclass bits that use those files you're adding to build Debian packages, they look good, so +1 on that.
Hopefully I'll finish my xenclient-sbuild.bbclass soon, and we can switch everything to it.

Regarding the files you're removing, sounds like they don't hurt anything, and at least one person is using them, so I suggest we keep them, maybe with a note somewhere mentioning that they're only there for development purposes.

**Comment by jean-edouard** [comment]
By the way this PR doesn't seem to build:

```
+ pushd pv-linux-drivers/xc-v4v
/home/build/builder/build/build/openxt/build/xctools/pv-linux-drivers/xc-v4v /home/build/builder/build/build/openxt/build/xctools
+ install -m 0644 -D dkms/lintian /home/build/builder/build/build/openxt/build/xctools/deb-tmp/data/usr/share/lintian/overrides/openxt-pv-v4v-dkms
install: cannot stat `dkms/lintian': No such file or directory
```

**Comment by jean-edouard** [comment]
This doesn't make much sense anymore after the modifications for the new build scripts.
@cjp256 please close this PR

**Pull request closed without merging**
